### ISSUE TITLE
Install instructions incomplete

### ISSUE THREAD

**Issue by KramNamez** [thinksabin/DTrackAuditor#10]
After using `pip install dtrack-auditor` the package is installed, but cannot be used as described. There's no module and digging into the site-packages to directly access dtrackauditor.py only leads to module/package errors.

Running the docker container after `docker pull thinksabin/dtrackauditor` just gives the same error.

```
Traceback (most recent call last):
  File "dtrackauditor.py", line 9, in <module>
    from dtrackauditor.auditor import Auditor
  File "/dtrackauditor.py", line 9, in <module>
    from dtrackauditor.auditor import Auditor
ModuleNotFoundError: No module named 'dtrackauditor.auditor'; 'dtrackauditor' is not a package
```

**Comment by thinksabin** [comment]
thanks for reporting. I will try to replicate the issue.

**Comment by thinksabin** [comment]
After doing the pip install you can directly call the dtrackauditor script using command dtrackauditor.
`thinksabin@DESKTOP:~$ pip install dtrack-auditor
thinksabin@DESKTOP:~$ dtrackauditor`

I have updated the docker image and also updated the readme doc. Hope this help. Please let me know if issue persist.
thanks.

**Comment by jimklimov** [comment]
Also check if #25 and #26 address it, making developer usability better?

**Comment by thinksabin** [comment]
thanks @jimklimov
