### ISSUE TITLE
Vulnerability rules failing even when configured with false

### ISSUE THREAD

**Issue by corvusmod** [thinksabin/DTrackAuditor#19]
Summary:
Configured rules but setting them as false, the command should return 0 and it returns 1

Command:
dtrackauditor -u https://host -k key -p test -v master -f bom.json -a -w -r critical:1:**false**,high:2:**false**,medium:10:**false**,low:10:**false**
Provided project name and version:  test master
Auto mode ON
Uploading bom.json ...
Waiting for bom to be processed on dt server ...
Processing token uuid is -------
No policy violations found.
{'CRITICAL': 2, 'HIGH': 5, 'MEDIUM': 4, 'LOW': 1, 'UNASSIGNED': 1}
Threshold for %s severity issues exceeded.

echo $?
1

**Comment by thinksabin** [comment]
hi @corvusmod
I have corrected the issue. Please let me know if this issue exist. Thanks.
