### ISSUE TITLE
Add support for setting the parent project in DT 

### ISSUE THREAD

**Issue by andy778** [thinksabin/DTrackAuditor#20]
I tough first it was a limitation in this software but it was also missing from the API, but that is now merged it looks like https://github.com/DependencyTrack/dependency-track/pull/2545

**Comment by andy778** [comment]
Version 4.8.0 seems to support this 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/10696501/233080875-a9bf73d6-954e-4da9-acac-66f45c51844f.png">

**Comment by thinksabin** [comment]
@andy778 thanks for information. I will look into it.

**Comment by jimklimov** [comment]
I think it could be a method similar to https://github.com/thinksabin/DTrackAuditor/pull/30/files#diff-f9984f110542a151439be91eaac59153b53aa189c0f811134c3f5a879a943b78R640-R670

The critical part REST API wise is to send a PATCH request with desired field. Schema for the DT version of choice can be seen in your API server under `/api/swagger.json` and I found a browsable variant (not sure how much up to date) at https://yoursky.blue/documentation/rest-api

**Comment by andy778** [comment]
> I think it could be a method similar to: https://github.com/thinksabin/DTrackAuditor/pull/30/files#diff-f9984f110542a151439be91eaac59153b53aa189c0f811134c3f5a879a943b78R640-R670
> 
> ...or as in another location - just using an inline JSON definition of the one-value payload: https://github.com/thinksabin/DTrackAuditor/pull/30/files#diff-f9984f110542a151439be91eaac59153b53aa189c0f811134c3f5a879a943b78R603-R606
> 
> The critical part REST API wise is to send a PATCH request with desired field. Schema for the DT version of choice can be seen in your API server under `/api/swagger.json` and I found a browsable variant (not sure how much up to date) at https://yoursky.blue/documentation/rest-api

I made a [PR 21](https://github.com/thinksabin/DTrackAuditor/pull/21) in May and updated now to align with the latest master

**Comment by jimklimov** [comment]
Should be finally in the codebase after PR #32 gets merged

**Comment by jimklimov** [comment]
Note: My idea about using a HTTP PATCH request to move a project into under a parent was not yet explored nor implemented. Probably worth another issue, if someone needs that trickery :)
