### ISSUE TITLE
GitHub action for "Scorecard Analysis" still fails

### ISSUE THREAD

**Issue by jimklimov** [thinksabin/DTrackAuditor#73]
The recently merged PR #71 succeeded to fix some of the actions that failed on master-branch builds before, but the scorecard still fails. I have never worked with it before, so would not tell heads from tails here ;)

https://github.com/thinksabin/DTrackAuditor/actions/runs/10981579809/job/30488787298

Note the comment from #71 still applies (so maybe locating and using release versions of the actions is the needed trick?):

> In `scorecard.yml` I tentatively proposed to use the newer releases rather than older snapshots by commit ID, but ossf/sarif actions remain referenced by ID for now, not sure what to do with those at the moment. I do not know why commit hashes were used in the first place...

**Comment by thinksabin** [comment]
I think it is recommended to use the commit hashes. Generally its one of the best practice to use commit hashes. I will try to fix it as per your suggestion. thanks.

**Comment by thinksabin** [comment]
deleted the workflow and added it again. resolved for now. thanks.
