### ISSUE TITLE
Unexpected behaviour with version 1.4.0

### ISSUE THREAD

**Issue by admabr** [thinksabin/DTrackAuditor#79]
Hello, we use `dtrackauditor` for vulnerability scanning, and everything worked smoothly until version 1.4.0. With this version, when a project doesn’t exist, the tool throws an exception stating that it cannot upload the bom.json. However, the bom.json does get uploaded successfully to the server (as I can see the project being created and the results available). On retrying the process, it completes without any errors.

I use the following flags: 

```
dtrackauditor -u "${DTRACK_URL}" \
      -k "${DTRACK_API_KEY}" \
      -p "${CI_PROJECT_PATH}" \
      -v "${VERSION}" \
      --parent_project "$parent_project" \
      -f bom.json \
      -a \
      --wait \
      -r critical:1:true,high:2:true,medium:10:true,low:10:false
```
And this is the output:

```
Uploading bom.json ...
Cannot get project 'xxx' 'yyy' id: 404 Not Found
Cannot get project '' (for 'xxx' 'yyy') info details before SBOM upload: 
Waiting for bom to be processed on dt server ...
Cannot get project '' (for 'xxx' 'yyy') info details after SBOM upload: 
AuditorException.INSTANT_EXIT: Cannot upload bom.json: project '' (for 'xxx' 'yyy') info details report a bogus lastBomImport value: None
```

**Comment by jimklimov** [comment]
Thanks, did not happen in my use-case (mostly as a library not standalone tool), will try to check soon-ish... likely not before next week.

**Comment by jimklimov** [comment]
In your example, `'xxx' 'yyy'` refers to... what exactly? A `'$parent_project' '$VERSION'`?

Is it uploading something new from scratch, or (cloning and?) inheriting from an older revision of a project?

**Comment by admabr** [comment]
Thanks for your response. Yes, they correspond to `'$parent_project' '$VERSION'` and it's creating them from scratch. For reference, it used to work with `1.3.0`, so nothing changed from our side.

**Comment by jimklimov** [comment]
At face value (by output here and memory about code), seems like a simple oversight of caring about original (known-absent) project's details and failing that they are not seen. Some missed `if ... is not None`.

**Comment by jimklimov** [comment]
So my first guess was close to home.

The methods which `get_project_with{,out}_version_id()`, and also `get_dependencytrack_version()`, are divided in their behavior for problem handling: they `return None` if the HTTP request succeeded (HTTP-200) but the reply did not have the UUID for that project name/version, or `return ""` if there was an HTTP request error (e.g. HTTP-404 here) but no lower-level errors (can not contact server etc. which would likely raise exceptions of their own) and if we did not throw any further exceptions other than an `AuditorRESTAPIException` which we catch and process for pretty reporting.

Notably, we do not re-raise a caught `AuditorRESTAPIException` (the idea is there, commented away) - only report it.

Ultimately, the uploading code did check for `None` but not for an empty string `""`, causing the problem.

Working on a PR to fix.

**Comment by jimklimov** [comment]
PR #81 was posted :)
